group 'io.paratoner.flutter_tesseract_ocr'
version '1.0'

plugins {
    id 'com.android.library'
}

repositories {
    google()
    mavenCentral()

    flatDir {
        dirs 'libs'
    }
}

android {
    namespace 'io.paratoner.flutter_tesseract_ocr'
    compileSdk 36

    defaultConfig {
        minSdk 21
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    lint {
        disable 'InvalidPackage'
    }
}

dependencies {
    api(name: 'tesseract4android-release', ext: 'aar')
}
